const Orders = [
  {
    productName: "Nike Air Jordan Shoe",
    productNumber: "X 24",
    paymentStatus: "Due",
    shippingStatus: "Pending",
  },
  {
    productName: "Nike Air Force Shoe",
    productNumber: "X 24",
    paymentStatus: "Refunded",
    shippingStatus: "Declined",
  },
  {
    productName: "Nike Dunke",
    productNumber: "X 24",
    paymentStatus: "Due",
    shippingStatus: "Pending",
  },
  {
    productName: "Nike Air Max Shoe",
    productNumber: "X 24",
    paymentStatus: "Paid",
    shippingStatus: "Delivered",
  },
  {
    productName: "Puma White Sneakes",
    productNumber: "X 24",
    paymentStatus: "Due",
    shippingStatus: "Pending",
  },
  {
    productName: "Puma Xcode full",
    productNumber: "X 24",
    paymentStatus: "REfunded",
    shippingStatus: "Declined",
  },
  {
    productName: "Adidas Superstar",
    productNumber: "X 24",
    paymentStatus: "Paid",
    shippingStatus: "Delivered",
  },
  {
    productName: "Roadster Cargo Jeans",
    productNumber: "X 24",
    paymentStatus: "Due",
    shippingStatus: "Pending",
  },
  {
    productName: "Mongos Cotton Pant",
    productNumber: "X 24",
    paymentStatus: "REfunded",
    shippingStatus: "Declined",
  },
  {
    productName: "Velvet Hoodie by Samy Robbins",
    productNumber: "X 24",
    paymentStatus: "Due",
    shippingStatus: "Pending",
  },
  {
    productName: "Rolex R500",
    productNumber: "X 24",
    paymentStatus: "REfunded",
    shippingStatus: "Declined",
  },
  {
    productName: "Titan Pure Leather Watch",
    productNumber: "X 24",
    paymentStatus: "Due",
    shippingStatus: "Pending",
  },
  {
    productName: "Giva Stianless Stell Locket",
    productNumber: "X 24",
    paymentStatus: "Due",
    shippingStatus: "Pending",
  },
  {
    productName: "Versace Bucket Hat",
    productNumber: "X 24",
    paymentStatus: "REfunded",
    shippingStatus: "Declined",
  },
  {
    productName: "Gucci Perfune ",
    productNumber: "X 24",
    paymentStatus: "Due",
    shippingStatus: "Pending",
  },
  {
    productName: "Prada HandBag",
    productNumber: "X 24",
    paymentStatus: "REfunded",
    shippingStatus: "Declined",
  },
  {
    productName: "G-force 39 Jacket",
    productNumber: "X 24",
    paymentStatus: "Paid",
    shippingStatus: "Delivered",
  },
  {
    productName: "Zara Oversize Tshirt",
    productNumber: "X 24",
    paymentStatus: "Due",
    shippingStatus: "Pending",
  },
];
